"""initial migration

Revision ID: c305ed9e36b5
Revises: 
Create Date: 2026-05-03 10:42:48.137074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c305ed9e36b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('schedule_name', sa.String(length=100), nullable=True),
    sa.Column('time_in', sa.DateTime(), nullable=False),
    sa.Column('time_out', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('subjects_attended', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='attendance'
    )
    with op.batch_alter_table('attendance_logs', schema='attendance') as batch_op:
        batch_op.create_index('ix_alog_department', ['department'], unique=False)
        batch_op.create_index('ix_alog_status', ['status'], unique=False)
        batch_op.create_index('ix_alog_time_in', ['time_in'], unique=False)
        batch_op.create_index('ix_alog_timein_utype', ['time_in', 'user_type'], unique=False)
        batch_op.create_index('ix_alog_uid', ['uid'], unique=False)
        batch_op.create_index('ix_alog_user_type', ['user_type'], unique=False)

    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rtsp_url', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('grid_position', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='attendance'
    )
    op.create_table('class_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('year_level', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('schedule_data', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='attendance'
    )
    op.create_table('event_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='attendance'
    )
    op.create_table('faculty',
    sa.Column('indx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('profile_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('indx'),
    sa.UniqueConstraint('indx'),
    sa.UniqueConstraint('uid'),
    schema='attendance'
    )
    op.create_table('pairing_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('pairing_code', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='attendance'
    )
    op.create_table('rpi_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('is_paired', sa.Boolean(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('pairing_code', sa.String(length=10), nullable=True),
    sa.Column('pairing_expires', sa.DateTime(), nullable=True),
    sa.Column('config_data', sa.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('scanner_mode', sa.String(length=20), nullable=True),
    sa.Column('auto_shutdown_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_shutdown_time', sa.String(length=5), nullable=True),
    sa.Column('ssh_username', sa.String(length=50), nullable=True),
    sa.Column('ssh_password', sa.String(length=255), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=True),
    sa.Column('pending_command', sa.String(length=50), nullable=True),
    sa.Column('command_issued_at', sa.DateTime(), nullable=True),
    sa.Column('command_issued_by', sa.String(length=50), nullable=True),
    sa.Column('paired_at', sa.DateTime(), nullable=True),
    sa.Column('paired_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id'),
    schema='attendance'
    )
    op.create_table('sms_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile_num', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='attendance'
    )
    op.create_table('sms_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile_num', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='attendance'
    )
    op.create_table('students',
    sa.Column('indx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('year_level', sa.Integer(), nullable=True),
    sa.Column('schedule', sa.JSON(), nullable=True),
    sa.Column('profile_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('parent_contact', sa.String(length=20), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('indx'),
    sa.UniqueConstraint('indx'),
    sa.UniqueConstraint('uid'),
    schema='attendance'
    )
    op.create_table('user_tb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='attendance'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tb', schema='attendance')
    op.drop_table('students', schema='attendance')
    op.drop_table('sms_queue', schema='attendance')
    op.drop_table('sms_logs', schema='attendance')
    op.drop_table('rpi_devices', schema='attendance')
    op.drop_table('pairing_requests', schema='attendance')
    op.drop_table('faculty', schema='attendance')
    op.drop_table('event_schedule', schema='attendance')
    op.drop_table('class_schedule', schema='attendance')
    op.drop_table('cameras', schema='attendance')
    with op.batch_alter_table('attendance_logs', schema='attendance') as batch_op:
        batch_op.drop_index('ix_alog_user_type')
        batch_op.drop_index('ix_alog_uid')
        batch_op.drop_index('ix_alog_timein_utype')
        batch_op.drop_index('ix_alog_time_in')
        batch_op.drop_index('ix_alog_status')
        batch_op.drop_index('ix_alog_department')

    op.drop_table('attendance_logs', schema='attendance')
    # ### end Alembic commands ###
